### PR TITLE
Use specific COSMO commit

### PR DESCRIPTION
**Pull request by remodietlicher**
Adds an option (-a $COMMIT_HASH) to use a specific COSMO commit. This is helpful to find the exact COSMO commit that breaks the parser.

### CODE REVIEW

**Comment by clementval** [comment]
@remodietlicher Is it failing or you just add the option in case it will?

**Comment by remodietlicher** [comment]
Yes, there is an error while parsing the current COSMO master. Being able to test a specific COSMO versions seemed handy in that case.

**Comment by clementval** [comment]
@remodietlicher Ok. Curious to see what you guys added that break the parser ...

**Comment by lxavier** [comment]
so the issue was that there was a stella related flag still in this script "-DGCL_COM" and one commit in cosmo on 29.11 reintroduce some related code (which was also wrong).
So there is a PR in cosmo to fix, and this one to remove the macro which should not be there.
I also removed cosmo-pompa, we don't need to support it.
@clementval ready to merge, in case you have time to review, otherwise I'll merge once Travis is ok

**Comment by lxavier** [comment]
@clementval ok will need some help here travis fails with 
> The command "cabal update && cabal install ShellCheck" failed and exited with 1 during .
Any idea where I should fix that ?

**Review by clementval — APPROVED** [review]
I update the `.travis.yml` file since now spellcheck is by default on travis. I recommend you to use `shellcheck` for any bash script you write. It helps a lot. Travis was still failing because of two issues that I quickly fixed and pushed to the branch. So this can be merged.

**Pull request merged**
